using System.Collections.Generic;
using Map;
using UnityEngine;

namespace Generation {
    public class RoomShape : TileShape {
        public List<Vector2Int> Doors { get; }
        private RoomShape(TileShape other, List<Vector2Int> doors) : base(other) {
            Doors = doors;
            
            // should walls be generated by algorithms or should they be included?
            // most likely included along with windows
        }

        public static RoomShape FromTileShape(TileShape shape) {
            var doors = new List<Vector2Int>();
            
            // TODO
            
            return new RoomShape(shape, doors);
        }
    }
}
